[package]
authors = ["Jake McGinty <me@jakebot.org>"]
categories = ["network-programming", "os::unix-apis"]
description = "A helper to perform requests using the Linux netlink interface"
edition = "2021"
homepage = "https://github.com/tonarino/innernet"
keywords.workspace = true
license = "MIT"
name = "netlink-request"
publish = true
readme = "README.md"
repository = "https://github.com/tonarino/innernet"
version = "2.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
netlink-packet-core.workspace = true
netlink-packet-generic.workspace = true
netlink-packet-route.workspace = true
netlink-sys.workspace = true
nix = { version = "0.25", features = ["feature"] }
once_cell = "1"
